/* Ejercicios de la guía RAP 5, tal como aparecen en el documento del SENA. */
const G5={
 can:[
  {type:'mc',q:"I <em>___</em> swim, but I <em>___</em> dive.",o:["can / can't","can't / can","can / can"],a:"can / can't",e:"can para lo que sí; can't para lo que no."},
  {type:'mc',q:"<em>___</em> you speak Portuguese?",o:["Can","Do","Are"],a:"Can",e:"Para preguntar si alguien sabe: Can + persona + acción. Can you swim?"},
  {type:'mc',q:"My little brother <em>___</em> read yet. He is four.",o:["can't","doesn't can","can not to"],a:"can't",e:"La negativa es can't o cannot."},
  {type:'mc',q:"<em>___</em> I open the window, please?",o:["Can","Am","Do"],a:"Can",e:"Pedir permiso: Can I...?"},
  {type:'mc',q:"She <em>___</em> play the guitar very well.",o:["can","cans","can to"],a:"can",e:"Los modales no llevan -s ni to."},
  {type:'mc',q:"We <em>___</em> go to the park if it stops raining.",o:["can","can to","are can"],a:"can",e:"Posibilidad: can + acción sin cambios."},
  {type:'type',q:"Escribe en negativa: <em>I can come to your house today.</em>",a:["i can't come to your house today","i cannot come to your house today"],e:"can + not se escribe cannot o can't."},
  {type:'type',q:"Forma la pregunta: <em>your sister / can / cook</em>",a:["can your sister cook"],e:"Can + persona + acción: Can you swim?"},
  {type:'tf',text:"He can to ride a bike.",ok:false,right:"He can ride a bike.",e:"Después de can no va to."},
  {type:'order',es:"¿Puedes ayudarme con la tarea?",en:"Can you help me with the homework?",e:"Can + persona + acción: Can you swim?"}],
 should:[
  {type:'mc',q:"You look sick. You <em>___</em> see a doctor.",o:["should","shouldn't","can't"],a:"should",e:"Consejo: should."},
  {type:'mc',q:"You <em>___</em> study the night before the exam only.",o:["shouldn't","should","must"],a:"shouldn't",e:"Consejo negativo: shouldn't."},
  {type:'mc',q:"<em>___</em> I bring my notebook tomorrow?",o:["Should","Do","Am"],a:"Should",e:"Pedir consejo: Should I...?"},
  {type:'mc',q:"Children <em>___</em> eat more fruit.",o:["should","shoulds","should to"],a:"should",e:"Modal + acción sin cambios."},
  {type:'mc',q:"You are tired. You <em>___</em> go to bed early tonight.",o:["should","shouldn't","can't"],a:"should",e:"Recomendación."},
  {type:'mc',q:"We <em>___</em> arrive late to class.",o:["shouldn't","should","may"],a:"shouldn't",e:"Lo que no es recomendable."},
  {type:'type',q:"Da un consejo: <em>you / should / drink / more water</em>",a:["you should drink more water"],e:"should + acción sin cambios."},
  {type:'type',q:"Escribe en negativa: <em>You should talk during the exam.</em>",a:["you shouldn't talk during the exam","you should not talk during the exam"],e:"should not o shouldn't."},
  {type:'tf',text:"You should to rest.",ok:false,right:"You should rest.",e:"Después de should no va to."},
  {type:'order',es:"Deberías llamar a tu mamá.",en:"You should call your mom.",e:"should + acción sin cambios."}],
 must:[
  {type:'mc',q:"Students <em>___</em> wear a uniform at this school. It is the rule.",o:["must","mustn't","don't have to"],a:"must",e:"Obligación."},
  {type:'mc',q:"You <em>___</em> use your phone during the exam.",o:["mustn't","don't have to","should"],a:"mustn't",e:"Prohibición."},
  {type:'mc',q:"Tomorrow is Sunday, so I <em>___</em> get up early.",o:["don't have to","mustn't","can't"],a:"don't have to",e:"No es necesario."},
  {type:'mc',q:"My sister <em>___</em> study every afternoon.",o:["has to","have to","must to"],a:"has to",e:"Tercera persona: has to."},
  {type:'mc',q:"Yesterday I <em>___</em> walk home because the bus didn't come.",o:["had to","must","have to"],a:"had to",e:"Must no tiene pasado: had to."},
  {type:'mc',q:"<em>___</em> you <em>___</em> wear glasses to read?",o:["Do / have to","Must / to","Have / to"],a:"Do / have to",e:"Pregunta con have to."},
  {type:'type',q:"Prohíbe algo: <em>you / mustn't / touch / that</em>",a:["you mustn't touch that","you must not touch that"],e:"mustn't + acción sin cambios."},
  {type:'type',q:"Escribe que no es necesario: <em>we / not have to / pay</em>",a:["we don't have to pay","we do not have to pay"],e:"don't have to."},
  {type:'tf',text:"You don't have to smoke here. It is forbidden.",ok:false,right:"You mustn't smoke here. It is forbidden.",e:"Si está prohibido va mustn't."},
  {type:'order',es:"Tengo que terminar mi tarea esta noche.",en:"I have to finish my homework tonight.",e:"have to + acción sin cambios."}],
 flight:[
  {type:'mc',q:"You <em>___</em> eat a heavy meal before you fly.",o:["shouldn't","mustn't","don't have to"],a:"shouldn't",e:"Consejo, no prohibición."},
  {type:'mc',q:"Passengers <em>___</em> switch off all electronic devices.",o:["must","should","may"],a:"must",e:"Obligación de la aerolínea."},
  {type:'mc',q:"You <em>___</em> wear loose, comfortable clothes for your flight.",o:["should","mustn't","can't"],a:"should",e:"Recomendación."},
  {type:'mc',q:"Passengers <em>___</em> smoke during take-off and landing.",o:["mustn't","don't have to","should"],a:"mustn't",e:"Prohibido."},
  {type:'mc',q:"You <em>___</em> take a short walk around the cabin on a long flight.",o:["can","mustn't","have to"],a:"can",e:"Está permitido."},
  {type:'mc',q:"You <em>___</em> drink too much alcohol.",o:["shouldn't","have to","can"],a:"shouldn't",e:"Consejo negativo."},
  {type:'mc',q:"Large pets <em>___</em> go into the passenger cabin.",o:["can't","should","don't have to"],a:"can't",e:"No está permitido."},
  {type:'mc',q:"Passengers <em>___</em> label their luggage correctly.",o:["must","might","can't"],a:"must",e:"Obligación."},
  {type:'mc',q:"<em>___</em> I pay in dollars for duty-free items?",o:["Can","Must","Should"],a:"Can",e:"Pedir permiso o preguntar si se puede."},
  {type:'mc',q:"Cabin crew <em>___</em> stay calm during an emergency.",o:["have to","might","don't have to"],a:"have to",e:"Obligación del trabajo."}],
 bean:[
  {type:'mc',q:"He <em>___</em> take a number and wait for his turn.",o:["should","doesn't have to","can't"],a:"should",e:"Es lo recomendable en una fila."},
  {type:'order',es:"Ahora él debe buscarlo.",en:"Now he must look for it.",e:"must + acción sin cambios."},
  {type:'mc',q:"Mr Bean <em>___</em> use his mouth to take another number.",o:["might","must","would"],a:"might",e:"Es solo una posibilidad."},
  {type:'order',es:"Puede que él quiera besarla.",en:"He might want to kiss her.",e:"might + acción sin cambios."},
  {type:'order',es:"Puede que ella no se quede en el parque.",en:"She might not stay in the park.",e:"might not + acción sin cambios."},
  {type:'order',es:"Puede que el hombre note algo.",en:"The man might notice something.",e:"might + acción sin cambios."},
  {type:'mc',q:"He <em>___</em> drive a car with a broom.",o:["can't","can","must"],a:"can't",e:"Es imposible."},
  {type:'order',es:"Puede que ahora vaya muy rápido.",en:"He might go very fast now.",e:"might + acción sin cambios."},
  {type:'mc',q:"He <em>___</em> touch that.",o:["shouldn't","should","must"],a:"shouldn't",e:"No es recomendable."},
  {type:'order',es:"Debe de dolerle al doctor.",en:"It must hurt the doctor.",e:"must para deducir."}],
 seqguia:[
  {type:'mc',q:"Bella took off her slippers. <em>___</em>, she went to bed.",o:["Then","Because","However"],a:"Then",e:"Secuencia."},
  {type:'mc',q:"Greg didn't want to forget his meeting, <em>___</em> he put a reminder on his finger.",o:["so","because","although"],a:"so",e:"Resultado."},
  {type:'mc',q:"John took a bath early in the morning <em>___</em> he had to go to the doctor.",o:["because","so","however"],a:"because",e:"Razón."},
  {type:'mc',q:"Ben lost the boxing challenge. <em>___</em>, he didn't care.",o:["However","Because","Finally"],a:"However",e:"Contraste."},
  {type:'mc',q:"George got an A+ in English, <em>___</em> he felt really happy.",o:["so","but","before"],a:"so",e:"Resultado."},
  {type:'mc',q:"The family had dinner very quickly <em>___</em> they wanted to go to the museum.",o:["because","however","then"],a:"because",e:"Razón."},
  {type:'seq',q:"Ordena la mañana de John:",steps:["First, John woke up at six.","Then, he took a bath.","After that, he got dressed.","Finally, he went to the doctor."],e:"First, Then, After that, Finally."},
  {type:'type',q:"Une con un conector de resultado: <em>It was very cold, <em>___</em> I wore a jacket.</em>",a:["so"],e:"so introduce el resultado."}],
 port:{
  titulo:'Port Olimpic, Barcelona',
  texto:"The most important rebuilding for the 1992 Olympics in Barcelona was the demolition of the old industrial waterfront. Four kilometres of promenade and sandy beaches were made. The city council built two thousand apartments with parks and called the area Nova Icaria. This area is still known as Vila Olimpica because the Olympic athletes originally stayed there. On the seafront there are two very tall buildings. One of these towers is an office block, the other is a modern hotel. This area has shops and nightclubs, but the main reason for visiting is the two levels of restaurants around the marina. After lunch you can walk along the beach or sit in one of the cafés. The Parc de la Ciutadella has a large boating lake, orange groves and palm trees full of parrots. The park was originally the site of a fortress which Prosper Verboom built for Felipe V between 1715 and 1720. The architect Josep Fontsere designed the cascade in the park with the help of Antoni Gaudi, who was then still a young student. You can also visit the zoo in the city park. The zoo had a special design in which small pools of water separated the animals. The only known example of an albino gorilla, Snowflake, arrived at the zoo in 1966 when he was three years old. Nowadays you can also see dolphin and whale shows at the zoo.",
  qs:[
   {q:"What was at Barcelona's waterfront before the 1992 Olympic Games?",o:["An old industrial area","A large park","A football stadium"],a:"An old industrial area",e:"the demolition of the old industrial waterfront."},
   {q:"Why is the area known as Vila Olimpica?",o:["Because the Olympic athletes stayed there","Because it was built in 1992","Because the towers are there"],a:"Because the Olympic athletes stayed there",e:"because the Olympic athletes originally stayed there."},
   {q:"What is one of the two tall buildings on the seafront?",o:["A hotel","A school","A hospital"],a:"A hotel",e:"the other is a modern hotel."},
   {q:"What is the main reason for visiting the area?",o:["The restaurants around the marina","The nightclubs","The shops"],a:"The restaurants around the marina",e:"the main reason for visiting is the two levels of restaurants."},
   {q:"What can you do after lunch?",o:["Walk along the beach","Visit the fortress","Take a boat to the zoo"],a:"Walk along the beach",e:"After lunch you can walk along the beach."},
   {q:"What can you see in Parc de la Ciutadella?",o:["A boating lake and palm trees with parrots","A football field","A shopping centre"],a:"A boating lake and palm trees with parrots",e:"a large boating lake, orange groves and palm trees full of parrots."},
   {q:"When was the fortress built?",o:["Between 1715 and 1720","In 1992","In 1966"],a:"Between 1715 and 1720",e:"built for Felipe V between 1715 and 1720."},
   {q:"Who was Josep Fontsere?",o:["The architect of the cascade","A young student","An Olympic athlete"],a:"The architect of the cascade",e:"The architect Josep Fontsere designed the cascade."},
   {q:"What was special about the zoo's design?",o:["Small pools of water separated the animals","It had no cages at all","It was built for the Olympics"],a:"Small pools of water separated the animals",e:"small pools of water separated the animals."},
   {q:"Who was Snowflake?",o:["An albino gorilla","A dolphin","The zoo's architect"],a:"An albino gorilla",e:"The only known example of an albino gorilla, Snowflake."}]}
};
