/* Contenido nuevo de la guía RAP 5. Datos puros: explicaciones (R5L) y ejercicios (R5). */
const R5L={
 ab:{paras:[
  "Can significa poder o saber hacer algo. Sirve para hablar de habilidad (I can use Python), de permiso (Can I use your computer?) y de posibilidad (It can be dangerous).",
  "Could es el pasado de can: I could read when I was five (sabía leer, podía leer). También sirve para pedir algo con más cortesía que can: Could you help me?",
  "La forma nunca cambia. Después de can y could va el verbo en forma base, sin to y sin -s: She can speak English. La negativa es can't o cannot (se escribe junto) y couldn't. La pregunta se forma poniendo el modal antes del sujeto: Can you swim?",
  "Truco de pronunciación: en afirmativa, can casi no suena (kən). En negativa, can't se pronuncia con fuerza (kænt), aunque la t final casi no se oiga. En los ejercicios de escucha fíjate en qué palabra lleva la fuerza."],
  examples:[["I can use Python.","Sé usar Python."],["I can't come tomorrow.","No puedo venir mañana."],["I could swim when I was six.","Sabía nadar cuando tenía seis años."],["Can I use your charger?","¿Puedo usar tu cargador?"],["Could you help me, please?","¿Me podrías ayudar, por favor?"]]},
 ob:{paras:[
  "Must y have to expresan obligación: tener que o deber. Must se usa mucho en normas escritas y cuando el hablante siente que algo es necesario: You must wear your ID card. Have to se usa para obligaciones que vienen de afuera, como un horario o un jefe: I have to start work at seven.",
  "Have to cambia con el sujeto: I have to, she has to. La pregunta y la negativa usan do o does: Do you have to work on Saturdays? Must no tiene pasado; para el pasado se usa had to: Yesterday I had to stay late.",
  "Aquí está la confusión más común. Mustn't significa que está prohibido: You mustn't share your password. Don't have to significa que no es necesario, pero puedes hacerlo si quieres: You don't have to print the report.",
  "En español: mustn't es no debes; don't have to es no tienes que. Si la frase habla de una prohibición, usa mustn't. Si habla de algo opcional, usa don't have to."],
  examples:[["You must wear your ID card.","Debes llevar tu carné."],["I have to start work at seven.","Tengo que empezar a trabajar a las siete."],["She has to call the client.","Ella tiene que llamar al cliente."],["You mustn't share your password.","No debes compartir tu contraseña."],["You don't have to print the report.","No tienes que imprimir el informe."],["Yesterday I had to stay late.","Ayer tuve que quedarme hasta tarde."]]},
 ad:{paras:[
  "Should significa debería y sirve para dar consejos o recomendaciones: You should rest. La negativa es shouldn't: You shouldn't work all night. Para pedir consejo se pregunta: What should I do? o Should I call him?",
  "Ought to significa lo mismo que should, pero es más formal y siempre lleva to: You ought to read the manual.",
  "Had better (en forma corta 'd better) es un consejo más fuerte, con advertencia: You'd better save your work, or you will lose it. Después va el verbo en forma base, sin to.",
  "If I were you, I would... equivale a yo en tu lugar...: If I were you, I would ask the instructor. En esta expresión se usa were aunque el sujeto sea I.",
  "No confundas consejo con obligación: should es una recomendación; must y have to son obligaciones."],
  examples:[["You should rest.","Deberías descansar."],["You shouldn't work all night.","No deberías trabajar toda la noche."],["What should I do?","¿Qué debería hacer?"],["You ought to read the manual.","Deberías leer el manual."],["You'd better save your work.","Más te vale guardar tu trabajo."],["If I were you, I would ask the instructor.","Yo en tu lugar, le preguntaría al instructor."]]},
 po:{paras:[
  "May, might y could expresan que algo es posible pero no seguro. En español equivalen a puede que, quizás o a lo mejor: It might rain. The file may be in the other folder. The problem could be the cable.",
  "La negativa es may not o might not: He might not come today (puede que no venga). Couldn't no sirve para decir quizás no; significa no pudo, no podría o no puede ser.",
  "Cuando estás casi seguro de algo por la información que tienes, usa must be: He works twelve hours a day. He must be tired. Si estás casi seguro de que algo no es verdad, usa can't be: That can't be John. He is in Bogotá.",
  "May también sirve para pedir permiso de forma formal: May I come in?",
  "Ojo con maybe: es una sola palabra, significa quizás y suele ir al inicio de la oración: Maybe she will come. May es el modal y va antes del verbo: She may come."],
  examples:[["It might rain later.","Puede que llueva más tarde."],["He may be in the lab.","Puede que esté en el laboratorio."],["The problem could be the cable.","El problema podría ser el cable."],["She must be tired.","Seguro que está cansada."],["That can't be the manager.","Ese no puede ser el gerente."],["May I come in?","¿Puedo pasar?"]]},
 rq:{paras:[
  "Para pedirle algo a alguien hay tres niveles de cortesía: Can you...? es informal, Could you...? es más amable y Would you...? es muy cortés. Agregar please suena mejor: Could you close the door, please?",
  "Para pedir permiso usa Can I...?, Could I...? o May I...?, que es la más formal: May I ask a question?",
  "Para decir lo que quieres de forma educada usa I would like o I'd like (me gustaría) en lugar de I want: I'd like a coffee, please.",
  "Para ofrecer algo usa Would you like...?: Would you like some water? Para ofrecer ayuda usa Shall I...? o Can I...?: Shall I help you? Para proponer algo en grupo usa Shall we...?: Shall we start?",
  "Respuestas naturales: Sure, Of course, No problem. Para decir que no: I'm sorry, I can't. A Could you...? no se responde Yes, I could."],
  examples:[["Could you close the door, please?","¿Podrías cerrar la puerta, por favor?"],["Would you help me with this report?","¿Me ayudarías con este informe?"],["May I ask a question?","¿Puedo hacer una pregunta?"],["I'd like a coffee, please.","Me gustaría un café, por favor."],["Would you like some water?","¿Quieres un poco de agua?"],["Shall we start?","¿Empezamos?"]]},
 seq:{paras:[
  "Los conectores de secuencia ordenan los pasos de un proceso o de una historia: first o firstly (primero), second o secondly (segundo), then y next (luego), after that (después de eso), later (más tarde) y finally (por último).",
  "Al comienzo de la oración normalmente llevan coma (después de then es opcional): First, open the program. Then, type your password. Finally, click Save.",
  "Before (antes de) y after (después de) van con un sustantivo o con el verbo terminado en -ing: after lunch, before sending the report. También pueden ir con una oración completa: Wash your hands before you cook.",
  "Para explicar un proceso de tu trabajo usa el verbo en forma base sin sujeto, como una instrucción: First, check the visitor's ID. Then, register the name in the system."],
  examples:[["First, open the program.","Primero, abre el programa."],["Then, type your password.","Luego, escribe tu contraseña."],["After that, click Save.","Después de eso, haz clic en Guardar."],["Finally, close the window.","Por último, cierra la ventana."],["Before sending the report, check the data.","Antes de enviar el informe, revisa los datos."]]},
 cause:{paras:[
  "Causa. Because (porque) va con una oración completa: I was late because the bus broke down. Because of y due to (debido a) van con un sustantivo: The class was cancelled because of the rain.",
  "Resultado. So (así que) une dos ideas en la misma oración: It was raining, so I took a taxi. Therefore y as a result (por lo tanto, como resultado) suelen empezar otra oración y llevan coma: The server crashed. As a result, we lost two hours of work.",
  "Contraste. But (pero) va dentro de la oración: The app is fast, but it uses a lot of battery. However (sin embargo) empieza otra oración y lleva coma: The app is fast. However, it uses a lot of battery. Although (aunque) va con una oración, y en la otra parte no se usa but: Although it was difficult, we finished on time.",
  "Adición. And, also y as well as agregan información. Moreover (además) es más formal. Not only... but also significa no solo... sino también: She is not only a good programmer but also a good teacher."],
  examples:[["I was late because the bus broke down.","Llegué tarde porque el bus se varó."],["The class was cancelled because of the rain.","La clase se canceló por la lluvia."],["It was raining, so I took a taxi.","Estaba lloviendo, así que tomé un taxi."],["The app is fast. However, it uses a lot of battery.","La aplicación es rápida. Sin embargo, gasta mucha batería."],["Although it was difficult, we finished on time.","Aunque fue difícil, terminamos a tiempo."]]},
 read:{paras:[
  "Este texto sale de la guía RAP 5. Léelo con calma. Después responde las preguntas: en cada una puedes volver a abrir el texto.",
  "Fíjate en los conectores que usa (and, also, so, such as) y en los verbos en pasado."],
  passage:"The first Thanksgiving was in 1621. The Pilgrims were new to America and did not know how to grow food or hunt animals. Many of them died. The Native Americans helped the Pilgrims. They taught them how to grow corn, pumpkins and beans. They also taught the Pilgrims how to fish and hunt.\n\nIn the fall of 1621, the Pilgrims had a big harvest. They were very thankful, so they had a huge feast to celebrate the harvest and to give thanks to the Native Americans. The feast lasted for three days.\n\nNow, Thanksgiving is celebrated on the fourth Thursday of November. Families come together and eat a lot of food, such as turkey, cranberries and pumpkin pie. Everybody talks about what they are thankful for.",
  examples:[]},
 pv:{paras:[
  "Un phrasal verb es un verbo más una partícula (on, off, up, out, in, for); juntos tienen un significado nuevo. Turn es girar, pero turn off es apagar. Por eso hay que aprenderlos como una sola expresión.",
  "Muchos se usan en el trabajo con computadores: turn on y turn off (encender y apagar), log in y log out (iniciar y cerrar sesión), set up (configurar o instalar), back up (hacer una copia de seguridad) y shut down (apagar un sistema).",
  "Otros muy comunes: fill out o fill in (llenar un formulario), look for (buscar), find out (averiguar), figure out (entender o resolver), carry out (llevar a cabo), give up (rendirse), sign up (inscribirse) y run out of (quedarse sin).",
  "En los phrasal verbs separables (turn off, set up, fill out, back up), si el objeto es un pronombre va en medio: turn it off, no turn off it. Con un sustantivo sirven las dos formas: turn off the computer o turn the computer off. Otros no se separan nunca: look for it, run out of paper."],
  examples:[["Please turn off the computer.","Por favor, apaga el computador."],["I can't log in.","No puedo iniciar sesión."],["Back up your files every day.","Haz una copia de seguridad de tus archivos todos los días."],["Fill out this form, please.","Llena este formulario, por favor."],["I'm looking for my ID card.","Estoy buscando mi carné."],["Turn it off.","Apágalo."]]}
};

const R5={
 ab:[
  {type:'mc',q:"I <em>___</em> swim when I was six, but now I can't.",o:["could","can","must"],a:"could",e:"Habilidad en el pasado: could."},
  {type:'mc',q:"My sister <em>___</em> speak three languages.",o:["can","cans","can to"],a:"can",e:"Modal + acción sin cambios, sin -s y sin to."},
  {type:'mc',q:"<em>___</em> I use your charger, please?",o:["Can","Must","Should"],a:"Can",e:"Pedir permiso: Can I...?"},
  {type:'mc',q:"Sorry, I <em>___</em> come to the meeting tomorrow. I have a doctor's appointment.",o:["can't","mustn't","shouldn't"],a:"can't",e:"Algo que no es posible: can't."},
  {type:'mc',q:"When I was a child, I <em>___</em> use a computer. Now I program every day.",o:["couldn't","can't","mustn't"],a:"couldn't",e:"No poder en el pasado: couldn't."},
  {type:'mc',q:"<em>___</em> you speak more slowly, please?",o:["Could","Must","Should"],a:"Could",e:"Petición cortés: Could you...?"},
  {type:'type',q:"Ana <em>___</em> (sabe) install Linux. She learned last year.",a:["can","knows how to"],e:"Habilidad en presente: can."},
  {type:'type',q:"I <em>___</em> (no pude) open the file yesterday because it was damaged.",a:["couldn't","could not","wasn't able to","was not able to"],e:"No poder en el pasado: couldn't."},
  {type:'type',q:"Forma la pregunta: <em>you / can / fix / my laptop</em>",a:["can you fix my laptop"],e:"Para preguntar, el modal va primero: Can you fix...?"},
  {type:'tf',text:"He can to drive a car.",ok:false,right:"He can drive a car.",e:"Después de can no va to."},
  {type:'tf',text:"She cans play the guitar.",ok:false,right:"She can play the guitar.",e:"Con he, she o it el modal tampoco lleva -s: she can, no she cans."},
  {type:'tf',text:"Could you send me the report, please?",ok:true,right:"Could you send me the report, please?",e:"Petición cortés bien formada."},
  {type:'order',es:"¿Puedo abrir la ventana?",en:"Can I open the window?",e:"Permiso: Can I + acción sin cambios."},
  {type:'order',es:"No pude terminar el proyecto a tiempo.",en:"I couldn't finish the project on time.",e:"couldn't + acción sin cambios."}],
 ob:[
  {type:'mc',q:"Visitors <em>___</em> register at the entrance. It is the rule.",o:["must","mustn't","don't have to"],a:"must",e:"Una norma obligatoria: must."},
  {type:'mc',q:"You <em>___</em> use your phone in the laboratory. It is forbidden.",o:["mustn't","don't have to","can"],a:"mustn't",e:"Prohibido: mustn't."},
  {type:'mc',q:"Tomorrow is a holiday, so we <em>___</em> go to class.",o:["don't have to","mustn't","can't to"],a:"don't have to",e:"No es necesario: don't have to."},
  {type:'mc',q:"My brother <em>___</em> wear a uniform at work.",o:["has to","have to","must to"],a:"has to",e:"Tercera persona: has to."},
  {type:'mc',q:"Yesterday I <em>___</em> stay late to fix a bug.",o:["had to","must","have to"],a:"had to",e:"Must no tiene pasado; se usa had to."},
  {type:'mc',q:"<em>___</em> you <em>___</em> work on Saturdays?",o:["Do / have to","Must / to","Have / to"],a:"Do / have to",e:"Pregunta con have to: Do you have to...?"},
  {type:'type',q:"Programmers <em>___</em> (tienen que) test their code before they upload it.",a:["have to","must","need to"],e:"Obligación: have to o must."},
  {type:'type',q:"You <em>___</em> (no es necesario) bring a laptop. We have computers.",a:["don't have to","do not have to","don't need to","do not need to","needn't"],e:"No es necesario: don't have to."},
  {type:'type',q:"Employees <em>___</em> (está prohibido) share their passwords.",a:["mustn't","must not","can't","cannot","aren't allowed to","are not allowed to"],e:"Prohibición: mustn't."},
  {type:'type',q:"She <em>___</em> (tuvo que) call the client yesterday.",a:["had to"],e:"Obligación en pasado: had to."},
  {type:'tf',text:"You don't have to smoke here. It is forbidden.",ok:false,right:"You mustn't smoke here. It is forbidden.",e:"Si está prohibido es mustn't; don't have to significa que no es necesario."},
  {type:'tf',text:"He has to finish the report today.",ok:true,right:"He has to finish the report today.",e:"Tercera persona con has to."},
  {type:'tf',text:"I must to go now.",ok:false,right:"I must go now.",e:"Después de must no va to."},
  {type:'order',es:"No tienes que venir mañana.",en:"You don't have to come tomorrow.",e:"No es necesario: don't have to."},
  {type:'order',es:"Tenemos que hacer una copia de seguridad.",en:"We have to make a backup.",e:"Obligación: have to + acción sin cambios."}],
 ad:[
  {type:'mc',q:"You look tired. You <em>___</em> go to bed early.",o:["should","shouldn't","mustn't"],a:"should",e:"Consejo: should."},
  {type:'mc',q:"You <em>___</em> eat so much sugar. It's bad for you.",o:["shouldn't","don't have to","couldn't"],a:"shouldn't",e:"Consejo negativo: shouldn't."},
  {type:'mc',q:"If I <em>___</em> you, I would study the irregular verbs.",o:["were","am","will be"],a:"were",e:"If I were you es una frase fija: se dice were aunque sea I."},
  {type:'mc',q:"You'd better <em>___</em> your password now.",o:["change","to change","changing"],a:"change",e:"had better + acción sin cambios."},
  {type:'mc',q:"What <em>___</em> I say in the interview?",o:["should","ought","must to"],a:"should",e:"Pedir consejo: What should I...?"},
  {type:'mc',q:"You <em>___</em> to read the instructions before you start.",o:["ought","should","had better"],a:"ought",e:"Ought es el único que lleva to: ought to read."},
  {type:'type',q:"I think you <em>___</em> (deberías) talk to your instructor.",a:["should","ought to"],e:"Consejo: should."},
  {type:'type',q:"You <em>___</em> (no deberías) leave your computer unlocked.",a:["shouldn't","should not"],e:"Consejo negativo: shouldn't."},
  {type:'type',q:"If I were you, I <em>___</em> (would / will) practice every day.",a:["would"],e:"If I were you, I would..."},
  {type:'tf',text:"You should to rest more.",ok:false,right:"You should rest more.",e:"Después de should no va to."},
  {type:'tf',text:"You had better save the file now.",ok:true,right:"You had better save the file now.",e:"had better + acción sin cambios."},
  {type:'tf',text:"You ought read the manual.",ok:false,right:"You ought to read the manual.",e:"Ought siempre lleva to."},
  {type:'order',es:"Deberías pedir ayuda.",en:"You should ask for help.",e:"should + acción sin cambios."},
  {type:'order',es:"Yo en tu lugar, revisaría el código otra vez.",en:"If I were you, I would check the code again.",alts:["I would check the code again if I were you."],e:"If I were you, I would + acción sin cambios."}],
 po:[
  {type:'mc',q:"Take an umbrella. It <em>___</em> rain later.",o:["might","must","has to"],a:"might",e:"Posibilidad: might."},
  {type:'mc',q:"I'm not sure where Luis is. He <em>___</em> be in the lab.",o:["may","must","can't"],a:"may",e:"No estás seguro: may."},
  {type:'mc',q:"She has worked for twelve hours. She <em>___</em> be very tired.",o:["must","might not","can't"],a:"must",e:"Deducción casi segura: must be."},
  {type:'mc',q:"That <em>___</em> be the manager. The manager is on vacation.",o:["can't","must","should"],a:"can't",e:"Deducción negativa: can't be."},
  {type:'mc',q:"Excuse me, <em>___</em> I come in? (permiso formal)",o:["May","Ought","Had better"],a:"May",e:"Permiso formal: May I...?"},
  {type:'mc',q:"We <em>___</em> not finish today. There is a lot of work.",o:["might","must","has"],a:"might",e:"might not: puede que no."},
  {type:'mc',q:"The error <em>___</em> be in the database or in the code. We don't know yet.",o:["could","must","has to"],a:"could",e:"Posibilidad: could."},
  {type:'type',q:"I <em>___</em> (quizás) go to the party. I'm not sure.",a:["might","may","could"],e:"Posibilidad: might, may o could."},
  {type:'type',q:"He <em>___</em> (puede que no) come today. He is sick.",a:["might not","may not"],e:"Posibilidad negativa: might not o may not."},
  {type:'type',q:"Your phone is ringing. Only your mom calls you at this time. It <em>___</em> (seguro que) be your mom.",a:["must"],e:"Deducción casi segura: must be."},
  {type:'tf',text:"It mights rain tomorrow.",ok:false,right:"It might rain tomorrow.",e:"Los modales no llevan -s."},
  {type:'tf',text:"He can't be at home. I saw him at SENA five minutes ago.",ok:true,right:"He can't be at home. I saw him at SENA five minutes ago.",e:"Deducción negativa bien usada."},
  {type:'tf',text:"She maybe come to the meeting.",ok:false,right:"She may come to the meeting.",e:"Maybe va solo al inicio: Maybe she will come. Pegado a la acción va may: She may come."},
  {type:'order',es:"Puede que (yo) llegue tarde.",en:"I might arrive late.",e:"might + acción sin cambios."}],
 rq:[
  {type:'mc',q:"<em>___</em> you like a cup of coffee?",o:["Would","Should","Must"],a:"Would",e:"Ofrecer algo: Would you like...?"},
  {type:'mc',q:"I <em>___</em> like a chicken sandwich, please.",o:["would","will","am"],a:"would",e:"Pedir con cortesía: I would like."},
  {type:'mc',q:"<em>___</em> we start the meeting now?",o:["Shall","Ought","Had better"],a:"Shall",e:"Proponer algo en grupo: Shall we...?"},
  {type:'mc',q:"Could you <em>___</em> me the file, please?",o:["send","to send","sending"],a:"send",e:"Could you + acción sin cambios."},
  {type:'mc',q:"A: Could you help me with this printer? B: <em>___</em>",o:["Sure, no problem.","Yes, I could.","No, you mustn't."],a:"Sure, no problem.",e:"A Could you...? se responde Sure u Of course, no Yes, I could."},
  {type:'mc',q:"May I <em>___</em> a question?",o:["ask","asking","to ask"],a:"ask",e:"May I + acción sin cambios."},
  {type:'type',q:"Pide con cortesía: <em>you / could / open / the door / please</em>",a:["could you open the door please","could you open the door, please","could you please open the door","please could you open the door"],e:"Could you + acción sin cambios + please."},
  {type:'type',q:"Ofrece ayuda: <em>I / shall / help you</em>",a:["shall i help you"],e:"Ofrecer ayuda: Shall I help you?"},
  {type:'type',q:"I <em>___</em> (me gustaría) a glass of water, please.",a:["would like","'d like"],e:"I would like o I'd like."},
  {type:'tf',text:"Would you like to dance?",ok:true,right:"Would you like to dance?",e:"Would you like + to + verbo."},
  {type:'tf',text:"Can you to help me?",ok:false,right:"Can you help me?",e:"Después de can no va to."},
  {type:'tf',text:"I would like a coffee, please.",ok:true,right:"I would like a coffee, please.",e:"Forma educada de pedir."},
  {type:'order',es:"¿Podría repetir la pregunta, por favor?",en:"Could you repeat the question, please?",alts:["Could you please repeat the question?"],e:"Petición cortés."},
  {type:'order',es:"¿Te gustaría venir con nosotros?",en:"Would you like to come with us?",e:"Would you like + to + verbo."}],
 seq:[
  {type:'mc',q:"<em>___</em>, turn on the computer. Then, open the browser.",o:["First","Finally","However"],a:"First",e:"Primer paso: First."},
  {type:'mc',q:"Open the app. <em>___</em>, enter your username and password.",o:["Then","Before","Because"],a:"Then",e:"Siguiente paso: Then."},
  {type:'mc',q:"Type your text and check it. <em>___</em>, click Save and close the program.",o:["Finally","Firstly","Although"],a:"Finally",e:"Último paso: Finally."},
  {type:'mc',q:"Wash your hands <em>___</em> you cook.",o:["before","after that","finally"],a:"before",e:"before + oración completa."},
  {type:'mc',q:"<em>___</em> lunch, we went back to the office.",o:["After","Then","Firstly"],a:"After",e:"After + una cosa: after lunch."},
  {type:'mc',q:"We tested the system. <em>___</em>, we showed it to the client.",o:["After that","Before","Firstly"],a:"After that",e:"After that: después de eso."},
  {type:'mc',q:"Before <em>___</em> the report, check the data.",o:["sending","send","to send"],a:"sending",e:"before o after + verbo con -ing."},
  {type:'seq',q:"Ordena los pasos para registrar a un visitante:",steps:["First, ask the visitor for their ID card.","Then, type the visitor's name in the system.","After that, print a badge with the name.","Finally, give the badge to the visitor."],e:"First, Then, After that, Finally."},
  {type:'seq',q:"Ordena la noche de Bella:",steps:["First, Bella put on her pajamas.","Then, she got into bed and read a book.","After that, she turned off the light.","Finally, she fell asleep."],e:"First, Then, After that, Finally."},
  {type:'seq',q:"Ordena los pasos para instalar un programa:",steps:["First, download the installer.","Next, open the file.","Then, accept the terms and click Install.","Finally, click Finish."],e:"First, Next, Then, Finally."},
  {type:'type',q:"<em>___</em> (Primero), log in to the platform.",a:["first","firstly","first of all"],e:"Primer paso: First o Firstly."},
  {type:'tf',text:"After finish the task, send me an email.",ok:false,right:"After finishing the task, send me an email.",e:"After + verbo con -ing."}],
 cause:[
  {type:'mc',q:"I stayed at home <em>___</em> I was sick.",o:["because","so","however"],a:"because",e:"Causa: because."},
  {type:'mc',q:"I was sick, <em>___</em> I stayed at home.",o:["so","because","although"],a:"so",e:"Resultado: so."},
  {type:'mc',q:"The flight was delayed <em>___</em> the bad weather.",o:["because of","because","so"],a:"because of",e:"because of + una cosa: because of the rain."},
  {type:'mc',q:"The program is free. <em>___</em>, it has some ads.",o:["However","Because","Because of"],a:"However",e:"Contraste al inicio de oración: However."},
  {type:'mc',q:"<em>___</em> it was difficult, we finished on time.",o:["Although","Because","Therefore"],a:"Although",e:"Although: aunque."},
  {type:'mc',q:"She speaks English <em>___</em> French.",o:["as well as","however","because of"],a:"as well as",e:"Adición: as well as."},
  {type:'mc',q:"The server crashed. <em>___</em>, we lost two hours of work.",o:["As a result","Although","Before"],a:"As a result",e:"Resultado: As a result."},
  {type:'mc',q:"He is not only a good programmer <em>___</em> a good teacher.",o:["but also","and also","however"],a:"but also",e:"not only... but also."},
  {type:'type',q:"I was late <em>___</em> (porque) the bus broke down.",a:["because","since","as"],e:"because + oración."},
  {type:'type',q:"It was raining, <em>___</em> (así que) I took a taxi.",a:["so"],e:"Resultado: so."},
  {type:'type',q:"The app is fast. <em>___</em> (Sin embargo), it uses a lot of battery.",a:["however","nevertheless"],e:"However al inicio, con coma."},
  {type:'tf',text:"I was late because of the traffic.",ok:true,right:"I was late because of the traffic.",e:"because of + una cosa: because of the rain."},
  {type:'tf',text:"I stayed home because of I was sick.",ok:false,right:"I stayed home because I was sick.",e:"Si sigue una frase completa, como I was sick, va because y no because of."},
  {type:'tf',text:"Although it was late, but we continued.",ok:false,right:"Although it was late, we continued.",e:"Con although no se usa but en la otra parte."},
  {type:'order',es:"Estudié mucho, así que aprobé el examen.",en:"I studied a lot, so I passed the exam.",e:"so + resultado."}],
 read:[
  {type:'mc',ctx:true,q:"When was the first Thanksgiving?",o:["In 1621","In 1492","In 1776"],a:"In 1621",e:"The first Thanksgiving was in 1621."},
  {type:'mc',ctx:true,q:"Who helped the Pilgrims?",o:["The Native Americans","The king of England","Other Pilgrims"],a:"The Native Americans",e:"The Native Americans helped the Pilgrims."},
  {type:'mc',ctx:true,q:"What did the Native Americans teach the Pilgrims?",o:["To grow corn and to fish","To build ships","To read and write"],a:"To grow corn and to fish",e:"They taught them how to grow corn and how to fish and hunt."},
  {type:'mc',ctx:true,q:"How long did the first feast last?",o:["Three days","One day","A week"],a:"Three days",e:"The feast lasted for three days."},
  {type:'mc',ctx:true,q:"When is Thanksgiving celebrated now?",o:["On the fourth Thursday of November","On the last Friday of November","On December 25th"],a:"On the fourth Thursday of November",e:"It is celebrated on the fourth Thursday of November."},
  {type:'mc',ctx:true,q:"What is a feast?",o:["A big meal to celebrate something","A kind of harvest","A religious song"],a:"A big meal to celebrate something",e:"A feast is a big meal for a celebration."},
  {type:'mc',ctx:true,q:"What do families eat on Thanksgiving now?",o:["Turkey, cranberries and pumpkin pie","Pizza and hamburgers","Rice and chicken"],a:"Turkey, cranberries and pumpkin pie",e:"such as turkey, cranberries and pumpkin pie."},
  {type:'mc',ctx:true,q:"They were very thankful, <em>___</em> they had a huge feast. ¿Qué conector usa el texto?",o:["so","however","although"],a:"so",e:"so introduce el resultado."},
  {type:'talk',q:"What are you thankful for? Answer with one or two sentences.",hint:"Usa I am thankful for...",groups:[["thankful","grateful","thank","thanks"]],min:5,model:"I am thankful for my family and for my classes at SENA."}],
 pv:[
  {type:'mc',q:"Please <em>___</em> the computer when you leave.",o:["turn off","turn up","look for"],a:"turn off",e:"turn off: apagar."},
  {type:'mc',q:"I can't <em>___</em>. I forgot my password.",o:["log in","give up","pick up"],a:"log in",e:"log in: iniciar sesión."},
  {type:'mc',q:"We need to <em>___</em> the database every night.",o:["back up","fill in","find out"],a:"back up",e:"back up: hacer una copia de seguridad."},
  {type:'mc',q:"Visitors must <em>___</em> this form at the entrance.",o:["fill out","turn off","set up"],a:"fill out",e:"fill out: llenar un formulario."},
  {type:'mc',q:"I'm <em>___</em> my keys. Have you seen them?",o:["looking for","looking after","giving up"],a:"looking for",e:"look for: buscar."},
  {type:'mc',q:"Don't <em>___</em>! You are almost finished.",o:["give up","log out","shut down"],a:"give up",e:"give up: rendirse."},
  {type:'mc',q:"Can you help me <em>___</em> the new printer?",o:["set up","run out","check in"],a:"set up",e:"set up: configurar o instalar."},
  {type:'mc',q:"We <em>___</em> of paper, so we couldn't print the report.",o:["ran out","found out","carried out"],a:"ran out",e:"run out of: quedarse sin."},
  {type:'mc',q:"The technician turned the server off. Con pronombre: The technician turned <em>___</em> off.",o:["it","him","its"],a:"it",e:"Con pronombre, va en medio: turned it off."},
  {type:'type',q:"I need to <em>___</em> (averiguar) why the system is slow.",a:["find out","figure out"],e:"find out: averiguar."},
  {type:'type',q:"Please <em>___</em> (cierra sesión) before you leave.",a:["log out","sign out","log off"],e:"log out: cerrar sesión."},
  {type:'type',q:"The company <em>___</em> (llevó a cabo) a security test last week.",a:["carried out","conducted","performed"],e:"carry out en pasado: carried out."},
  {type:'tf',text:"Please turn off it.",ok:false,right:"Please turn it off.",e:"Con pronombre, el pronombre va en medio."},
  {type:'tf',text:"I signed up for an English course.",ok:true,right:"I signed up for an English course.",e:"sign up for: inscribirse en."},
  {type:'order',es:"Recuerda cerrar sesión.",en:"Remember to log out.",e:"remember to + verbo."}]
};

/* Frases para leer y repetir en voz alta (la app escucha y compara). */
const R5SAY={
 modals:[["I can speak a little English.","Sé hablar un poco de inglés."],["Could you repeat that, please?","¿Podrías repetir eso, por favor?"],["You must wear your ID card.","Debes llevar tu carné."],["You don't have to print the report.","No tienes que imprimir el informe."],["You mustn't share your password.","No debes compartir tu contraseña."],["You should test the code first.","Deberías probar el código primero."],["It might rain this afternoon.","Puede que llueva esta tarde."],["Would you like some coffee?","¿Quieres un café?"],["May I ask a question?","¿Puedo hacer una pregunta?"],["If I were you, I would practice every day.","Yo en tu lugar, practicaría todos los días."]],
 linking:[["First, open the program.","Primero, abre el programa."],["Then, type your username and password.","Luego, escribe tu usuario y contraseña."],["After that, click the save button.","Después de eso, haz clic en el botón de guardar."],["Finally, close the window.","Por último, cierra la ventana."],["I was late because the bus broke down.","Llegué tarde porque el bus se varó."],["It was raining, so I took a taxi.","Estaba lloviendo, así que tomé un taxi."],["The app is fast. However, it uses a lot of battery.","La aplicación es rápida. Sin embargo, gasta mucha batería."],["Although it was difficult, we finished on time.","Aunque fue difícil, terminamos a tiempo."]],
 phrasal:[["Please turn off the computer.","Por favor, apaga el computador."],["I need to log in to the platform.","Necesito iniciar sesión en la plataforma."],["Don't forget to back up your files.","No olvides hacer una copia de seguridad de tus archivos."],["Can you help me set up the printer?","¿Me ayudas a instalar la impresora?"],["We ran out of paper.","Nos quedamos sin papel."],["I'm looking for my ID card.","Estoy buscando mi carné."]]
};

/* Preguntas para responder hablando: la app revisa que uses la estructura pedida. */
const R5TALK={
 modals:[
  {q:"What must you do before you enter the SENA center?",hint:"Usa must o have to.",groups:[["must","have to","has to"]],min:5,model:"I must show my ID card at the entrance."},
  {q:"What mustn't you do in the computer lab?",hint:"Usa mustn't o can't.",groups:[["must not","cannot","not allowed","must never","can never"]],min:5,model:"We mustn't eat or drink in the computer lab."},
  {q:"Give advice to a new classmate.",hint:"Usa should, ought to o had better.",groups:[["should","ought to","had better","if i were you"]],min:4,model:"You should practice English every day."},
  {q:"Ask your instructor for permission to leave early.",hint:"Usa Can I, Could I o May I.",groups:[["can i","could i","may i"]],min:4,model:"Could I leave class early today, please?"},
  {q:"Ask a colleague to help you. Be polite.",hint:"Usa Could you o Would you.",groups:[["could you","would you","can you"]],min:4,model:"Could you help me with this report, please?"},
  {q:"What might happen if you don't back up your files?",hint:"Usa might, may o could.",groups:[["might","may","could"]],min:4,model:"I might lose all my work."},
  {q:"Say something you don't have to do on weekends.",hint:"Usa don't have to.",groups:[["do not have to","does not have to"]],min:5,model:"I don't have to wake up early on weekends."}],
 linking:[
  {q:"Explain the first two steps to log in to a platform.",hint:"Usa First y Then.",groups:[["first","firstly"],["then","next","after that","second","secondly"]],min:6,model:"First, open the website. Then, type your username and password."},
  {q:"Why do you study software development?",hint:"Usa because.",groups:[["because"]],min:5,model:"I study software development because I like technology."},
  {q:"Describe a problem at work and its result.",hint:"Usa so o as a result.",groups:[["so","as a result","therefore"]],min:6,model:"The internet was very slow, so we couldn't upload the project."},
  {q:"Say one good thing and one bad thing about your phone.",hint:"Usa but o however.",groups:[["but","however","although","though"]],min:6,model:"My phone has a good camera, but the battery is bad."}],
 phrasal:[
  {q:"What do you do when you finish working on the computer?",hint:"Usa log out, turn off o shut down.",groups:[["log out","log off","sign out","turn off","turn it off","turn the computer off","switch off","switch it off","shut down","shut it down","shut the computer down"]],min:4,model:"I log out and turn off the computer."},
  {q:"What should you do with your important files every day?",hint:"Usa back up.",groups:[["back up","backup","back them up","back it up","back my files up","make a backup"]],min:4,model:"I should back up my important files every day."}]
};
