/* Verbos de las dos hojas impresas: [verbo, pasado, participio, español]. */
const HOJA1=[
 ["answer","answered","answered","responder"],["arrive","arrived","arrived","llegar"],["ask","asked","asked","preguntar"],
 ["be","was/were","been","ser"],["borrow","borrowed","borrowed","tomar prestado"],["break","broke","broken","romper"],
 ["buy","bought","bought","comprar"],["catch","caught","caught","atrapar"],["clean","cleaned","cleaned","limpiar"],
 ["climb","climbed","climbed","escalar"],["collect","collected","collected","coleccionar"],["come","came","come","venir"],
 ["compose","composed","composed","componer"],["cook","cooked","cooked","cocinar"],["cut","cut","cut","cortar"],
 ["dance","danced","danced","bailar"],["describe","described","described","describir"],["discover","discovered","discovered","descubrir"],
 ["do","did","done","hacer"],["drink","drank","drunk","beber"],["drive","drove","driven","conducir"],
 ["eat","ate","eaten","comer"],["enjoy","enjoyed","enjoyed","disfrutar"],["fall","fell","fallen","caer"],
 ["feel","felt","felt","sentir"],["find","found","found","encontrar"],["fly","flew","flown","volar"],
 ["forget","forgot","forgotten","olvidar"],["give","gave","given","dar"],["go","went","gone","ir"],
 ["happen","happened","happened","suceder"],["have","had","had","tener"],["help","helped","helped","ayudar"],
 ["hurt","hurt","hurt","herir, doler"],["invent","invented","invented","inventar"],["invite","invited","invited","invitar"],
 ["kill","killed","killed","matar"],["know","knew","known","saber"],["lend","lent","lent","prestar"],
 ["leave","left","left","dejar"],["lie","lay","lain","yacer"],["like","liked","liked","gustar"],
 ["live","lived","lived","vivir"],["look","looked","looked","mirar"],["love","loved","loved","amar"],
 ["make","made","made","hacer"],["meet","met","met","conocer, encontrar"],["miss","missed","missed","perder, extrañar"],
 ["open","opened","opened","abrir"],["pack","packed","packed","empacar"],["pay","paid","paid","pagar"],
 ["phone","phoned","phoned","llamar por teléfono"],["play","played","played","jugar"],["prefer","preferred","preferred","preferir"],
 ["prepare","prepared","prepared","preparar"],["push","pushed","pushed","empujar"],["put","put","put","poner"],
 ["rain","rained","rained","llover"],["read","read","read","leer"],["remember","remembered","remembered","recordar"],
 ["rent","rented","rented","alquilar"],["rescue","rescued","rescued","rescatar"],["return","returned","returned","volver, devolver"],
 ["ring","rang","rung","llamar por teléfono"],["save","saved","saved","ahorrar"],["say","said","said","decir"],
 ["search","searched","searched","buscar"],["see","saw","seen","ver"],["sell","sold","sold","vender"],
 ["sit","sat","sat","sentarse"],["skate","skated","skated","patinar"],["ski","skied","skied","esquiar"],
 ["sleep","slept","slept","dormir"],["smell","smelled","smelled","oler"],["speak","spoke","spoken","hablar"],
 ["spend","spent","spent","gastar"],["start","started","started","comenzar"],["stay","stayed","stayed","quedarse"],
 ["stop","stopped","stopped","detener"],["study","studied","studied","estudiar"],["survive","survived","survived","sobrevivir"],
 ["swim","swam","swum","nadar"],["take","took","taken","tomar"],["talk","talked","talked","hablar"],
 ["teach","taught","taught","enseñar"],["tell","told","told","decir"],["think","thought","thought","pensar"],
 ["throw","threw","thrown","lanzar"],["touch","touched","touched","tocar"],["try","tried","tried","intentar"],
 ["understand","understood","understood","entender"],["use","used","used","usar"],["visit","visited","visited","visitar"],
 ["wait","waited","waited","esperar"],["walk","walked","walked","caminar"],["want","wanted","wanted","querer"],
 ["wash","washed","washed","lavar"],["watch","watched","watched","mirar"],["wear","wore","worn","llevar puesto"],
 ["work","worked","worked","trabajar"],["write","wrote","written","escribir"]];
const HOJA2=[
 ["awake","awoke","awoken","despertarse"],["be","was/were","been","ser o estar"],["bear","bore","born","soportar"],
 ["beat","beat","beaten","golpear"],["become","became","become","llegar a ser"],["begin","began","begun","empezar"],
 ["bend","bent","bent","doblar"],["bet","bet","bet","apostar"],["bind","bound","bound","atar"],
 ["bite","bit","bitten","morder"],["bleed","bled","bled","sangrar"],["blow","blew","blown","soplar"],
 ["break","broke","broken","romper"],["breed","bred","bred","criar"],["bring","brought","brought","traer, llevar"],
 ["broadcast","broadcast","broadcast","transmitir"],["build","built","built","construir"],["burn","burnt","burnt","quemar"],
 ["burst","burst","burst","reventar"],["buy","bought","bought","comprar"],["cast","cast","cast","arrojar"],
 ["catch","caught","caught","coger"],["come","came","come","venir"],["cost","cost","cost","costar"],
 ["cut","cut","cut","cortar"],["choose","chose","chosen","elegir"],["cling","clung","clung","adherirse"],
 ["creep","crept","crept","arrastrarse"],["deal","dealt","dealt","tratar"],["dig","dug","dug","cavar"],
 ["do","did","done","hacer"],["draw","drew","drawn","dibujar"],["dream","dreamt","dreamt","soñar"],
 ["drink","drank","drunk","beber"],["drive","drove","driven","conducir"],["eat","ate","eaten","comer"],
 ["fall","fell","fallen","caer"],["feed","fed","fed","alimentar"],["feel","felt","felt","sentir"],
 ["fight","fought","fought","luchar"],["find","found","found","encontrar"],["flee","fled","fled","huir"],
 ["fly","flew","flown","volar"],["forbid","forbade","forbidden","prohibir"],["forget","forgot","forgotten","olvidar"],
 ["forgive","forgave","forgiven","perdonar"],["forsake","forsook","forsaken","abandonar"],["freeze","froze","frozen","helar"],
 ["get","got","got","obtener"],["give","gave","given","dar"],["go","went","gone","ir"],
 ["grow","grew","grown","crecer"],["hang","hung","hung","colgar"],["have","had","had","haber o tener"],
 ["hear","heard","heard","oír"],["hide","hid","hidden","ocultar"],["hit","hit","hit","golpear"],
 ["hold","held","held","agarrar"],["hurt","hurt","hurt","herir"],["keep","kept","kept","conservar"],
 ["know","knew","known","saber o conocer"],["kneel","knelt","knelt","arrodillarse"],["knit","knit","knit","tejer"],
 ["lay","laid","laid","poner"],["lead","led","led","conducir, guiar"],["lean","leant","leant","apoyarse"],
 ["leap","leapt","leapt","brincar"],["learn","learnt","learnt","aprender"],["leave","left","left","dejar"],
 ["lend","lent","lent","prestar"],["let","let","let","permitir"],["lie","lay","lain","echarse"],
 ["light","lit","lit","encender"],["lose","lost","lost","perder"],["make","made","made","hacer"],
 ["mean","meant","meant","significar"],["meet","met","met","encontrarse"],["mistake","mistook","mistaken","equivocar"],
 ["pay","paid","paid","pagar"],["put","put","put","poner"],["read","read","read","leer"],
 ["ride","rode","ridden","montar"],["ring","rang","rung","llamar"],["rise","rose","risen","levantarse"],
 ["run","ran","run","correr"],["say","said","said","decir"],["see","saw","seen","ver"],
 ["seek","sought","sought","buscar"],["sell","sold","sold","vender"],["send","sent","sent","enviar"],
 ["set","set","set","poner(se)"],["sew","sewed","sewn","coser"],["shake","shook","shaken","sacudir"],
 ["shine","shone","shone","brillar"],["shoot","shot","shot","disparar"],["show","showed","shown","mostrar"],
 ["shrink","shrank","shrunk","encogerse"],["shut","shut","shut","cerrar"],["sing","sang","sung","cantar"],
 ["sink","sank","sunk","hundir"],["sit","sat","sat","sentarse"],["sleep","slept","slept","dormir"],
 ["slide","slid","slid","resbalar"],["smell","smelt","smelt","oler"],["sow","sowed","sown","sembrar"],
 ["speak","spoke","spoken","hablar"],["speed","sped","sped","acelerar"],["spell","spelt","spelt","deletrear"],
 ["spend","spent","spent","gastar"],["spill","spilt","spilt","derramar"],["spit","spat","spat","escupir"],
 ["split","split","split","dividir"],["spoil","spoilt","spoilt","estropear"],["stand","stood","stood","estar de pie"],
 ["steal","stole","stolen","robar"],["stick","stuck","stuck","pegar"],["sting","stung","stung","picar"],
 ["stink","stank","stunk","apestar"],["swear","swore","sworn","jurar"],["sweat","sweat","sweat","sudar"],
 ["sweep","swept","swept","barrer"],["swim","swam","swum","nadar"],["swing","swung","swung","columpiarse"],
 ["take","took","taken","coger, tomar"],["teach","taught","taught","enseñar"],["tear","tore","torn","rasgar"],
 ["tell","told","told","decir"],["think","thought","thought","pensar"],["throw","threw","thrown","tirar"],
 ["tread","trod","trodden","pisar"],["understand","understood","understood","entender"],["wake","woke","woken","despertarse"],
 ["wear","wore","worn","llevar puesto"],["weep","wept","wept","llorar"],["wet","wet","wet","mojar"],
 ["win","won","won","ganar"],["wind","wound","wound","enrollar"],["write","wrote","written","escribir"]];
/* Formas también correctas que la hoja no trae (inglés de Estados Unidos). */
const VERB_ALT={burn:["burned"],dream:["dreamed"],lean:["leaned"],leap:["leaped"],learn:["learned"],smell:["smelled","smelt"],
 spell:["spelled"],spill:["spilled"],spoil:["spoiled"],kneel:["kneeled"],knit:["knitted"],sweat:["sweated"],wet:["wetted"],
 speed:["speeded"],get:["gotten"],awake:["awaked"],sew:["sewn"],sow:["sown"],show:["showed"]};
